# tools/project_tools.py
"""
Project packaging and documentation tools for CodeForge AI.

These tools handle:
  - Generating README.md files
  - Creating .gitignore files
  - Zipping the entire project for download
  - Saving project metadata (PRD, design system, etc.)
"""

import json
import zipfile
from pathlib import Path
from datetime import datetime
from crewai.tools import tool


# ---------------------------------------------------------------------------
# Helper: build a simple directory tree string (used inside README)
# ---------------------------------------------------------------------------
def _build_tree_string(directory: Path, prefix: str = "") -> str:
    """
    Recursively build a visual tree of the directory.

    Example output:
        my-project/
        ├── index.html
        ├── css/
        │   └── style.css
        └── js/
            └── main.js
    """
    if not directory.exists() or not directory.is_dir():
        return ""

    # Gather entries, skip noise
    skip_names = {"__pycache__", ".DS_Store", ".git", "node_modules", ".codeforge"}
    entries = sorted(
        [e for e in directory.iterdir() if e.name not in skip_names],
        key=lambda e: (e.is_file(), e.name.lower()),
    )

    lines = []
    for index, entry in enumerate(entries):
        is_last = index == len(entries) - 1
        connector = "└── " if is_last else "├── "
        lines.append(f"{prefix}{connector}{entry.name}")

        if entry.is_dir():
            extension = "    " if is_last else "│   "
            subtree = _build_tree_string(entry, prefix + extension)
            if subtree:
                lines.append(subtree)

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Tool 1: Generate README.md
# ---------------------------------------------------------------------------
@tool("generate_readme")
def generate_readme(
    project_path: str,
    project_name: str,
    description: str,
    tech_stack: str,
    features: str,
) -> str:
    """
    Generate a professional README.md file inside the project folder.

    Args:
        project_path: Absolute path to the project root folder.
        project_name: Human-readable project name (e.g. "AI Resume Builder").
        description: One-paragraph description of the project.
        tech_stack: Comma-separated technologies (e.g. "HTML5, Tailwind CSS, GSAP").
        features: Comma-separated key features (e.g. "Responsive, Animated, SEO").

    Returns:
        Success or error message.
    """
    try:
        root = Path(project_path)
        if not root.exists():
            return f"Error: Project folder not found at {project_path}"

        # --- Parse comma-separated lists into bullet points ---
        tech_bullets = "\n".join(
            f"- {t.strip()}" for t in tech_stack.split(",") if t.strip()
        )
        feature_bullets = "\n".join(
            f"- {f.strip()}" for f in features.split(",") if f.strip()
        )

        # --- Build the file tree for the README ---
        tree_lines = _build_tree_string(root)
        tree_block = f"```\n{root.name}/\n{tree_lines}\n```" if tree_lines else "```\n(empty)\n```"

        # --- Assemble the README content ---
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        readme_content = f"""# {project_name}

{description}

---

## 🚀 Tech Stack

{tech_bullets}

## ✨ Features

{feature_bullets}

## 📁 Project Structure

{tree_block}

## 🛠️ Setup & Installation

1. Download and extract the ZIP file.
2. Open the project folder in VS Code (or any editor).
3. Open `index.html` in your browser — no build step required.

## 📱 Responsive Design

This project is fully responsive and tested on:

| Breakpoint | Devices |
|---|---|
| 320px – 480px | Mobile phones |
| 768px – 1024px | Tablets |
| 1280px+ | Desktops & laptops |

## 🚢 Deployment

### Netlify (Drag & Drop)
1. Go to [app.netlify.com/drop](https://app.netlify.com/drop)
2. Drag the project folder onto the page
3. Done — you get a live URL instantly

### GitHub Pages
1. Push the project to a GitHub repository
2. Go to Settings → Pages → Source: `main` / `root`
3. Your site will be live at `https://<username>.github.io/<repo>`

### Vercel
1. Go to [vercel.com](https://vercel.com) and import the repo
2. Framework preset: `Other`
3. Click Deploy

## 📄 License

Generated by **CodeForge AI** — an AI-powered software house.

---

*Generated on {now}*
"""

        # --- Write the file ---
        readme_path = root / "README.md"
        readme_path.write_text(readme_content, encoding="utf-8")

        return f"README.md successfully created at {readme_path}"

    except Exception as e:
        return f"Error generating README: {str(e)}"


# ---------------------------------------------------------------------------
# Tool 2: Generate .gitignore
# ---------------------------------------------------------------------------
@tool("generate_gitignore")
def generate_gitignore(project_path: str) -> str:
    """
    Generate a .gitignore file with standard web-project ignore rules.

    Args:
        project_path: Absolute path to the project root folder.

    Returns:
        Success or error message.
    """
    try:
        root = Path(project_path)
        if not root.exists():
            return f"Error: Project folder not found at {project_path}"

        gitignore_content = """\
# ---- Dependencies ----
node_modules/
vendor/

# ---- Build Output ----
dist/
build/
out/
.next/

# ---- IDE / Editor ----
.vscode/
.idea/
*.swp
*.swo
*~

# ---- OS Files ----
.DS_Store
Thumbs.db
Desktop.ini

# ---- Environment ----
.env
.env.local
.env.*.local

# ---- Logs ----
*.log
npm-debug.log*

# ---- Temp ----
tmp/
temp/
*.tmp

# ---- Python ----
__pycache__/
*.py[cod]
*.egg-info/
venv/
"""

        gitignore_path = root / ".gitignore"
        gitignore_path.write_text(gitignore_content, encoding="utf-8")

        return f".gitignore successfully created at {gitignore_path}"

    except Exception as e:
        return f"Error generating .gitignore: {str(e)}"


# ---------------------------------------------------------------------------
# Tool 3: ZIP the project
# ---------------------------------------------------------------------------
@tool("zip_project")
def zip_project(project_path: str) -> str:
    """
    Compress the entire project folder into a .zip file for download.
    The ZIP is saved next to the project folder (inside workspace/).

    Args:
        project_path: Absolute path to the project root folder.

    Returns:
        Absolute path to the created .zip file, or an error message.
    """
    try:
        root = Path(project_path)
        if not root.exists():
            return f"Error: Project folder not found at {project_path}"

        # ZIP goes into the same parent directory as the project folder
        zip_path = root.parent / f"{root.name}.zip"

        # Files/folders to skip when zipping
        skip_names = {"__pycache__", ".DS_Store", ".git", "node_modules"}

        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for file_path in root.rglob("*"):
                if file_path.is_file() and file_path.name not in skip_names:
                    # Store paths relative to the project's parent so the
                    # top-level folder inside the ZIP is the project name
                    arcname = file_path.relative_to(root.parent)
                    zf.write(file_path, arcname)

        size_kb = zip_path.stat().st_size / 1024
        return f"ZIP created at {zip_path.resolve()} ({size_kb:.1f} KB)"

    except Exception as e:
        return f"Error creating ZIP: {str(e)}"


# ---------------------------------------------------------------------------
# Tool 4: Save project metadata
# ---------------------------------------------------------------------------
@tool("save_project_metadata")
def save_project_metadata(project_path: str, metadata: str) -> str:
    """
    Save project metadata (PRD, design system, sitemap, etc.) as a JSON file
    inside a hidden .codeforge/ folder in the project.

    Args:
        project_path: Absolute path to the project root folder.
        metadata: A JSON string containing any project metadata.
                  If it is not valid JSON it will be stored as raw text.

    Returns:
        Success or error message.
    """
    try:
        root = Path(project_path)
        if not root.exists():
            return f"Error: Project folder not found at {project_path}"

        # Create hidden metadata directory
        meta_dir = root / ".codeforge"
        meta_dir.mkdir(parents=True, exist_ok=True)

        # Try to parse as JSON; fall back to wrapping raw text
        try:
            data = json.loads(metadata)
        except (json.JSONDecodeError, TypeError):
            data = {"raw_text": metadata}

        # Always stamp generation time
        data["generated_at"] = datetime.now().isoformat()
        data["project_path"] = str(root.resolve())

        # Write
        meta_file = meta_dir / "project_meta.json"
        meta_file.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")

        return f"Project metadata saved to {meta_file}"

    except Exception as e:
        return f"Error saving metadata: {str(e)}"